# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29646b85b20f77772d9fa4bcf8a20a3c48020b8e8d5189f5e2617546e38a889ffc44e5ce2518a1183c828784ca61e6c630b7ae2b29211875dd597269a204eb09

test:
  secret_key_base: 7d2243f123a27f08e710d6321b79d6838def8f4c35d0df2d270c622f31d719e1a18dfe659b5590473ac6a6dcf7fd2f0372e1abb4a8865de8fe7578b44b7c4b97

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
